package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/g4lb/autoresearch-go/internal/config"
	"github.com/g4lb/autoresearch-go/internal/discover"
	"github.com/g4lb/autoresearch-go/internal/gitx"
	"github.com/g4lb/autoresearch-go/templates"
)

// gitignoreEntries are the lines init adds to .gitignore. .autoresearch/*
// ignores everything the harness itself writes under that directory (e.g.
// Task 16's profile output under .autoresearch/profiles/), while the
// negation re-includes config.yaml — the one file under .autoresearch/ that
// is meant to be version-controlled, since humans own it and want their
// edits tracked. Note the "/*": git cannot re-include a file whose parent
// directory is itself excluded, so ".autoresearch/" followed by a negation
// would silently fail to un-ignore config.yaml; excluding the directory's
// contents and re-including the one file inside it is the form that works.
var gitignoreEntries = []string{".autoresearch/*", "!.autoresearch/config.yaml", "results.tsv", "run.log"}

// runInit scans a repository, discovers its benchmarks, and writes
// `.autoresearch/config.yaml` and `program.md`. It is the entry point every
// other command assumes has already run.
func runInit(args []string) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	dir := fs.String("C", ".", "repository root (or a directory inside it)")
	force := fs.Bool("force", false, "overwrite an existing .autoresearch/config.yaml")
	if err := fs.Parse(args); err != nil {
		return exitUsage
	}

	root, err := gitx.Root(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: %s is not inside a git repository: %v\n", *dir, err)
		fmt.Fprintln(os.Stderr, "autoresearch-go needs git to keep or discard each experiment; run `git init` first.")
		return exitUsage
	}

	configPath := filepath.Join(root, config.Path)
	if _, statErr := os.Stat(configPath); statErr == nil && !*force {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: %s already exists; pass -force to overwrite\n", configPath)
		return exitUsage
	}

	benches, err := discover.Benchmarks(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: %v\n", err)
		return exitUsage
	}
	if len(benches) == 0 {
		fmt.Fprintln(os.Stderr, "autoresearch-go init: no benchmarks found. autoresearch-go optimizes what it "+
			"can measure — add a Benchmark function first, or see the README section \"Repos with no benchmarks\".")
		return exitUsage
	}
	names := discover.BaseNames(benches)

	cfg := config.Default()
	cfg.Benchmarks = names

	if err := os.MkdirAll(filepath.Dir(configPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: %v\n", err)
		return exitUsage
	}
	if err := os.WriteFile(configPath, renderConfig(cfg), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: write config: %v\n", err)
		return exitUsage
	}

	programPath := filepath.Join(root, "program.md")
	if err := os.WriteFile(programPath, templates.ProgramMD(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: write program.md: %v\n", err)
		return exitUsage
	}

	if err := ensureGitignore(root, gitignoreEntries); err != nil {
		fmt.Fprintf(os.Stderr, "autoresearch-go init: update .gitignore: %v\n", err)
		return exitUsage
	}

	printInitSummary(names, configPath, programPath)
	return exitOK
}

// ensureGitignore appends whichever of entries are not already present as a
// line in root's .gitignore, creating the file if necessary. It never
// duplicates a line that is already there.
func ensureGitignore(root string, entries []string) error {
	path := filepath.Join(root, ".gitignore")
	existing := map[string]bool{}
	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		content = nil
	}
	for _, line := range strings.Split(string(content), "\n") {
		existing[strings.TrimSpace(line)] = true
	}

	var missing []string
	for _, e := range entries {
		if !existing[e] {
			missing = append(missing, e)
		}
	}
	if len(missing) == 0 {
		return nil
	}

	var buf bytes.Buffer
	buf.Write(content)
	if len(content) > 0 && !bytes.HasSuffix(content, []byte("\n")) {
		buf.WriteByte('\n')
	}
	for _, e := range missing {
		buf.WriteString(e)
		buf.WriteByte('\n')
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// renderConfig writes cfg as YAML with an explanatory comment above every
// field, so a human opening the file for the first time understands each
// knob without leaving it. config.Load tolerates comments and applies
// defaults for anything an editing human later removes.
func renderConfig(cfg config.Config) []byte {
	var b strings.Builder
	b.WriteString("# autoresearch-go run configuration.\n")
	b.WriteString("# Generated by `autoresearch-go init`. Safe to hand-edit; comments are not\n")
	b.WriteString("# preserved by future automated writes, but init only writes this file once\n")
	b.WriteString("# (or with -force).\n\n")

	b.WriteString("# Benchmarks declares exactly which benchmark functions count toward the\n")
	b.WriteString("# score. autoresearch-go discovered these when you ran `init`; edit this\n")
	b.WriteString("# list by hand to narrow or widen what gets measured. Empty means every\n")
	b.WriteString("# discovered benchmark.\n")
	writeYAMLList(&b, "benchmarks", cfg.Benchmarks)
	b.WriteString("\n")

	b.WriteString("# Scope lists the package patterns (Go import path patterns, e.g. ./...)\n")
	b.WriteString("# the agent is allowed to edit. Anything outside these patterns is rejected\n")
	b.WriteString("# by the scope gate before it is even built.\n")
	writeYAMLList(&b, "scope", cfg.Scope)
	b.WriteString("\n")

	b.WriteString("# Count is the number of interleaved A/B measurement rounds per side.\n")
	b.WriteString("# Higher counts are slower to run but more resistant to noise. 4 is the hard\n")
	b.WriteString("# floor: below it the significance test can never report p < 0.05, so every\n")
	b.WriteString("# experiment would be discarded no matter how large the real improvement is.\n")
	b.WriteString("# Below about 8, significance gets hard to reach on a noisy machine even for a\n")
	b.WriteString("# genuine win. The default of 10 leaves real margin; lower it for speed only if\n")
	b.WriteString("# you accept more experiments coming back DISCARD on noise alone.\n")
	fmt.Fprintf(&b, "count: %d\n\n", cfg.Count)

	b.WriteString("# Benchtime is passed to `go test -benchtime` for each round.\n")
	fmt.Fprintf(&b, "benchtime: %s\n\n", cfg.Benchtime)

	b.WriteString("# Race enables -race during the correctness gate (never during measurement,\n")
	b.WriteString("# which would distort timings). Recommended: leave this on.\n")
	fmt.Fprintf(&b, "race: %t\n\n", cfg.Race)

	b.WriteString("# MaxRegressPct is the largest tolerated statistically significant\n")
	b.WriteString("# regression, as a percentage. Any benchmark that regresses more than this\n")
	b.WriteString("# rejects the whole experiment, however good the overall score.\n")
	fmt.Fprintf(&b, "max_regress_pct: %s\n\n", strconv.FormatFloat(cfg.MaxRegressPct, 'g', -1, 64))

	b.WriteString("# GOMAXPROCS pins parallelism during measurement for more repeatable\n")
	b.WriteString("# numbers. 0 leaves GOMAXPROCS alone.\n")
	fmt.Fprintf(&b, "gomaxprocs: %d\n\n", cfg.GOMAXPROCS)

	b.WriteString("# Timeout bounds each subprocess phase (build, vet, test, benchmark).\n")
	fmt.Fprintf(&b, "timeout: %s\n\n", cfg.Timeout)

	b.WriteString("# Unfreeze lists test files deliberately exempted from the baseline freeze —\n")
	b.WriteString("# normally empty. Only add a file here if you specifically want the agent\n")
	b.WriteString("# to be able to edit it, understanding that this weakens the guarantee that\n")
	b.WriteString("# tests can't be gamed.\n")
	writeYAMLList(&b, "unfreeze", cfg.Unfreeze)

	return []byte(b.String())
}

// writeYAMLList renders a YAML block-sequence field, or "key: []" when empty.
func writeYAMLList(b *strings.Builder, key string, items []string) {
	if len(items) == 0 {
		fmt.Fprintf(b, "%s: []\n", key)
		return
	}
	fmt.Fprintf(b, "%s:\n", key)
	for _, item := range items {
		fmt.Fprintf(b, "  - %s\n", item)
	}
}

// printInitSummary reports what init found and wrote, and the exact next
// commands to run.
func printInitSummary(benchmarks []string, configPath, programPath string) {
	fmt.Printf("autoresearch-go init: found %d benchmark(s):\n", len(benchmarks))
	for _, n := range benchmarks {
		fmt.Printf("  - %s\n", n)
	}
	fmt.Println("\nwrote:")
	fmt.Printf("  %s\n", configPath)
	fmt.Printf("  %s\n", programPath)
	fmt.Println("\nnext:")
	fmt.Println("  git add -A && git commit -m \"autoresearch-go init\"")
	fmt.Println("  autoresearch-go doctor")
	fmt.Printf("  autoresearch-go baseline -tag %s\n", defaultTag())
}

// defaultTag suggests a run tag from today's date, e.g. "sep4".
func defaultTag() string {
	return strings.ToLower(time.Now().Format("Jan2"))
}
